name: weather_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  flutter_native_splash: 2.2.9
  dio: ^5.3.2
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.0

flutter_native_splash:
  color: '#F9CA50'
  image: lib/assets/images/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/city.list.json